name: Backup DB
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Test connection
        run: |
          psql \
          "host=${{ secrets.DB_HOST }}" \
          "user=${{ secrets.DB_USER }}" \
          "dbname=ayric" \
          "sslmode=require" \  # ← Critical SSL fix
          -c "SELECT 1;"
        env:
          PGPASSWORD: ${{ secrets.DB_PASS }}

      - name: Dump database
        run: |
          pg_dump \
          --host=${{ secrets.DB_HOST }} \
          --username=${{ secrets.DB_USER }} \
          --dbname=ayric \
          --ssl-mode=require \  # ← Critical SSL fix
          --file=backup.sql
        env:
          PGPASSWORD: ${{ secrets.DB_PASS }}

      - name: Upload backup
        uses: actions/upload-artifact@v4
        with:
          name: db-backup-$(date +%Y-%m-%d)
          path: backup.sql
