name: Backup DB
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client jq  # Added jq here

      - name: Get GitHub IPs (debug)
        run: |
          curl -s https://api.github.com/meta > meta.json
          echo "GitHub IPs:"
          jq -r '.actions[]' meta.json

      - name: Test connection
        run: |
          psql \
          "host=${{ secrets.DB_HOST }}" \
          "user=${{ secrets.DB_USER }}" \
          "dbname=ayric" \
          -c "SELECT 1;"
        env:
          PGPASSWORD: ${{ secrets.DB_PASS }}

      - name: Dump database
        run: |
          pg_dump \
          --host=${{ secrets.DB_HOST }} \
          --username=${{ secrets.DB_USER }} \
          --dbname=ayric \
          --file=backup.sql \
          --no-password
        env:
          PGPASSWORD: ${{ secrets.DB_PASS }}

      - name: Upload backup
        uses: actions/upload-artifact@v4
        with:
          name: db-backup-$(date +%Y-%m-%d)
          path: backup.sql
